// Some of these may be unused or from Labo Toy-Con Garage, which Game Builder Garage is based on
export enum ActorType {
  Invalid = 'Invalid',
  Expander = 'Expander', // unused?
  Wire = 'Wire', // unused?
  FoundIrMarkerNode = 'FoundIrMarkerNode',
  IsHoldPianoKeyNode = 'IsHoldPianoKeyNode', // unused?
  RobotRightArmNode = 'RobotRightArmNode', // unused?
  RobotLeftArmNode = 'RobotLeftArmNode', // unused?
  RobotRightFootNode = 'RobotRightFootNode', // unused?
  RobotLeftFootNode = 'RobotLeftFootNode', // unused?
  BikeHandleNode = 'BikeHandleNode', // unused?
  BikeAccelNode = 'BikeAccelNode', // unused?
  BikeWheelieNode = 'BikeWheelieNode', // unused?
  FishRodNode = 'FishRodNode', // unused?
  FishReelNode = 'FishReelNode', // unused?
  IsDetectHouseDeviceNode = 'IsDetectHouseDeviceNode', // unused?
  HouseSnapNode = 'HouseSnapNode', // unused?
  HouseSnapTrigNode = 'HouseSnapTrigNode', // unused?
  HouseButtonNode = 'HouseButtonNode', // unused?
  HouseRotationNode = 'HouseRotationNode', // unused?
  StickTiltedNode = 'StickTiltedNode', // unused?
  IsControllerSwingedNode = 'IsControllerSwingedNode', // unused?
  IsConsoleSwingedNode = 'IsConsoleSwingedNode', // unused?
  IsControllerSurfaceUpwardNode = 'IsControllerSurfaceUpwardNode', // unused?
  IsConsoleSurfaceUpwardNode = 'IsConsoleSurfaceUpwardNode', // unused?
  ButtonPressedNode = 'ButtonPressedNode',
  IsTouchNode = 'IsTouchNode',
  VibrateNode = 'VibrateNode',
  GaugeNode = 'GaugeNode',
  FlashNode = 'FlashNode', // unused?
  PlaySoundScaleNode = 'PlaySoundScaleNode', // unused?
  PlaySoundEffectNode = 'PlaySoundEffectNode', // unused?
  EmitIrLedNode = 'EmitIrLedNode',
  AndNode = 'AndNode',
  NotNode = 'NotNode',
  FlagNode = 'FlagNode',
  TimerNode = 'TimerNode',
  CounterNode = 'CounterNode',
  SpoitNode = 'SpoitNode',
  CommentNode = 'CommentNode',
  SignalViewerNode = 'SignalViewerNode', // unused?
  IsDetectMtrDeviceNode = 'IsDetectMtrDeviceNode', // unused?
  MtrPedalAccelNode = 'MtrPedalAccelNode', // unused?
  MtrPedalTrigNode = 'MtrPedalTrigNode', // unused?
  MtrPlaneStickNode = 'MtrPlaneStickNode', // unused?
  MtrPlaneButtonNode = 'MtrPlaneButtonNode', // unused?
  MtrCarHandleNode = 'MtrCarHandleNode', // unused?
  MtrCarActionLeverNode = 'MtrCarActionLeverNode', // unused?
  MtrCarGimmickChangeNode = 'MtrCarGimmickChangeNode', // unused?
  MtrCarPullLeverNode = 'MtrCarPullLeverNode', // unused?
  MtrCarJumpTrigNode = 'MtrCarJumpTrigNode', // unused?
  MtrCarBackLeverNode = 'MtrCarBackLeverNode', // unused?
  MtrSubmarineHandleNode = 'MtrSubmarineHandleNode', // unused?
  MtrSubmarineButtonNode = 'MtrSubmarineButtonNode', // unused?
  OutputDetectedMtrDeviceNode = 'OutputDetectedMtrDeviceNode', // unused?
  OutputMtrCarHandleNode = 'OutputMtrCarHandleNode', // unused?
  OutputMtrCarActionLeverNode = 'OutputMtrCarActionLeverNode', // unused?
  OutputMtrCarGimmickChangeNode = 'OutputMtrCarGimmickChangeNode', // unused?
  OutputMtrCarPullLeverNode = 'OutputMtrCarPullLeverNode', // unused?
  OutputMtrCarJumpTrigNode = 'OutputMtrCarJumpTrigNode', // unused?
  OutputMtrCarBackLeverNode = 'OutputMtrCarBackLeverNode', // unused?
  OutputMtrPedalAccelNode = 'OutputMtrPedalAccelNode', // unused?
  OutputMtrPedalTrigNode = 'OutputMtrPedalTrigNode', // unused?
  OutputMtrPlaneStickNode = 'OutputMtrPlaneStickNode', // unused?
  OutputMtrPlaneButtonNode = 'OutputMtrPlaneButtonNode', // unused?
  OutputMtrSubmarineHandleNode = 'OutputMtrSubmarineHandleNode', // unused?
  OutputMtrSubmarineButtonNode = 'OutputMtrSubmarineButtonNode', // unused?
  PlayBgmNode = 'PlayBgmNode',
  Move2dNode = 'Move2dNode',
  CalculationNode = 'CalculationNode',
  QuantizationNode = 'QuantizationNode',
  AlwaysOnNode = 'AlwaysOnNode',
  IsRotateControllerNode = 'IsRotateControllerNode', // unused?
  IsRotateConsoleNode = 'IsRotateConsoleNode', // unused?
  EconomyRateNode = 'EconomyRateNode', // unused?
  GasolineRemainingNode = 'GasolineRemainingNode', // unused?
  OutputMtrHornButtonNode = 'OutputMtrHornButtonNode', // unused?
  OutputMtrChangeCameraButtonNode = 'OutputMtrChangeCameraButtonNode', // unused?
  OutputMtrRotateCameraNode = 'OutputMtrRotateCameraNode', // unused?
  AngleDistanceNode = 'AngleDistanceNode',
  ControllerRotationAngleNode = 'ControllerRotationAngleNode', // unused?
  ConsoleRotationAngleNode = 'ConsoleRotationAngleNode', // unused?
  SelectedGimmickNode = 'SelectedGimmickNode', // unused?
  CurrentVehicleNode = 'CurrentVehicleNode', // unused?
  IsCameraFirstPersonNode = 'IsCameraFirstPersonNode', // unused?
  IsPlayerInTheWaterNode = 'IsPlayerInTheWaterNode', // unused?
  IsPlayerInTheAirNode = 'IsPlayerInTheAirNode', // unused?
  MtrNullStickNode = 'MtrNullStickNode', // unused?
  OutputMtrNullStickNode = 'OutputMtrNullStickNode', // unused?
  OutputMtrRumbleSettingNode = 'OutputMtrRumbleSettingNode', // unused?
  RandomNode = 'RandomNode', // unused?
  IntegerRandomNode = 'IntegerRandomNode',
  OnStartNode = 'OnStartNode',
  PlzObjBreakCountNode = 'PlzObjBreakCountNode',
  PlzUserMoveRigidNode = 'PlzUserMoveRigidNode', // unused?
  PlzGentenNode = 'PlzGentenNode', // unused?
  PlzRigidNode = 'PlzRigidNode',
  PlzCommentRigidNode = 'PlzCommentRigidNode',
  PlzScoreRigidNode = 'PlzScoreRigidNode',
  PlzMoveRigidNode = 'PlzMoveRigidNode',
  PlzRotateRigidNode = 'PlzRotateRigidNode',
  PlzStretchRigidNode = 'PlzStretchRigidNode',
  PlzPullForceNode = 'PlzPullForceNode',
  PlzGeneratorNode = 'PlzGeneratorNode',
  PlzRopeNode = 'PlzRopeNode',
  PlzSensorNode = 'PlzSensorNode',
  PlzTouchSensorNode = 'PlzTouchSensorNode',
  PlzObjWarpEnterNode = 'PlzObjWarpEnterNode',
  PlzObjWarpExitNode = 'PlzObjWarpExitNode',
  PlzFancyRigidNode = 'PlzFancyRigidNode',
  PlzDiceNode = 'PlzDiceNode', // unused?
  PlzHumanNode = 'PlzHumanNode',
  PlzCarNode = 'PlzCarNode',
  PlzUfoNode = 'PlzUfoNode',
  PlzStartPositionNode = 'PlzStartPositionNode', // unused?
  PlzHandNode = 'PlzHandNode',
  PlzHeadNode = 'PlzHeadNode',
  PlzCameraDirectionNode = 'PlzCameraDirectionNode',
  PlzCameraLookAtNode = 'PlzCameraLookAtNode',
  PlzCameraViewAngleNode = 'PlzCameraViewAngleNode',
  PlzWorldEffectNode = 'PlzWorldEffectNode', // unused?
  PlzCameraEffectNode = 'PlzCameraEffectNode', // unused?
  PlzPlaySpeedNode = 'PlzPlaySpeedNode',
  PlzGravityNode = 'PlzGravityNode',
  PlzAirResistanceNode = 'PlzAirResistanceNode', // unused?
  PlzFieldConfigNode = 'PlzFieldConfigNode',
  PlzResetNode = 'PlzResetNode',
  PlzExitNode = 'PlzExitNode',
  PlzChangeFileNode = 'PlzChangeFileNode',
  MainconCheckNode = 'MainconCheckNode', // unused?
  AttatchmentCheckNode = 'AttatchmentCheckNode', // unused?
  CvrCameraZoomNode = 'CvrCameraZoomNode', // unused?
  CvrWindmillBlowTrigNode = 'CvrWindmillBlowTrigNode', // unused?
  CvrWindmillRotationSpeedNode = 'CvrWindmillRotationSpeedNode', // unused?
  CvrBazookaHandlePositionNode =  'CvrBazookaHandlePositionNode', // unused?
  CvrBazookaBulletPositionNode = 'CvrBazookaBulletPositionNode', // unused?
  CvrBazookaIsBulletLoadedNode = 'CvrBazookaIsBulletLoadedNode', // unused?
  CvrBazookaBulletFireTrigNode = 'CvrBazookaBulletFireTrigNode', // unused?
  CvrBazookaTriggerTrigNode = 'CvrBazookaTriggerTrigNode', // unused?
  CvrBazookaVisorAngleNode = 'CvrBazookaVisorAngleNode', // unused?
  CvrPedalInputLevelNode = 'CvrPedalInputLevelNode', // unused?
  CvrPedalInputTrigNode = 'CvrPedalInputTrigNode', // unused?
  CvrBirdHeadPositionNode = 'CvrBirdHeadPositionNode', // unused?
  CvrBirdFlappingTrigNode = 'CvrBirdFlappingTrigNode', // unused?
  CvrElephantRelativePositionNode = 'CvrElephantRelativePositionNode', // unused?
  CvrElephantRelativeRotationNode =  'CvrElephantRelativeRotationNode', // unused?
  CvrDiverRelativePositionNode = 'CvrDiverRelativePositionNode', // unused?
  CvrDiverRelativeRotationNode = 'CvrDiverRelativeRotationNode', // unused?
  CvrDiverIsCaptureMarkerNode = 'CvrDiverIsCaptureMarkerNode', // unused?
  WireWarpInNode = 'WireWarpInNode',
  WireWarpOutNode ='WireWarpOutNode',
  ConstantNode = 'ConstantNode',
  MappingNode = 'MappingNode',
  RoundTripCounterNode = 'RoundTripCounterNode', // unused?
  PlzPositionSensorNode = 'PlzPositionSensorNode',
  PlzSpeedSensorNode ='PlzSpeedSensorNode',
  PlzAccelerationSensorNode = 'PlzAccelerationSensorNode',
  PlzAngleSensorNode = 'PlzAngleSensorNode',
  PlzRotationSensorNode = 'PlzRotationSensorNode',
  PlzBreakSensorNode = 'PlzBreakSensorNode',
  PlzBrokenSensorNode = 'PlzBrokenSensorNode',
  PlzGrabSensorNode = 'PlzGrabSensorNode',
  PlzJointSliderNode = 'PlzJointSliderNode',
  PlzJointHingeNode ='PlzJointHingeNode',
  PlzCameraPositionNode = 'PlzCameraPositionNode',
  PlzPlayerHeightNode = 'PlzPlayerHeightNode', // unused?
  CvrElephantIsCaptureMarkerNode = 'CvrElephantIsCaptureMarkerNode', // unused?
  PlzBindCommanderNode = 'PlzBindCommanderNode',
  ComparisonNode = 'ComparisonNode',
  TriggerNode = 'TriggerNode',
  AtanNode = 'AtanNode',
  TrigonometricNode = 'TrigonometricNode',
  SquareRootNode = 'SquareRootNode',
  PlzJointSingleAxisSliderNode = 'PlzJointSingleAxisSliderNode',
  PlzGeneratorFewNode = 'PlzGeneratorFewNode',
  PlzGeneratorManyNode = 'PlzGeneratorManyNode',
  IntegerCounterNode = 'IntegerCounterNode', // unused?
  PlzSoundEffectNode = 'PlzSoundEffectNode',
  PlzTextureNode = 'PlzTextureNode',
  AbsoluteValueNode = 'AbsoluteValueNode',
  NegationNode = 'NegationNode',
  TouchPositionNode = 'TouchPositionNode',
  PlzEasyCamera = 'PlzEasyCamera',
  PlzUseGyroCameraNode = 'PlzUseGyroCameraNode', // unused?
  TpbPuzzleClearNode = 'TpbPuzzleClearNode', // unused?
  TpbPuzzlePalletNode = 'TpbPuzzlePalletNode', // unused?
  TpbEventFlowNode = 'TpbEventFlowNode', // unused?
  PlzFingerNode = 'PlzFingerNode', // unused?
  IntegratedSurfaceUpwardNode = 'IntegratedSurfaceUpwardNode',
  IntegratedAxisAngleNode = 'IntegratedAxisAngleNode',
  PlzTpsCamera = 'PlzTpsCamera',
  TpbCounterNode = 'TpbCounterNode',
  TpbPlaySoundNode = 'TpbPlaySoundNode',
  TpbPlayBgmNode = 'TpbPlayBgmNode',
  PlzIntegratedEffectNode = 'PlzIntegratedEffectNode',
  IntegratedSwingedNode = 'IntegratedSwingedNode',
  IntegratedRotationSpeedNode = 'IntegratedRotationSpeedNode'
};